
<!doctype html>
<html class="no-js"  lang="en">

	<head>
		<!-- META DATA -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	<script type="text/javascript" src="http://gc.kis.v2.scr.kaspersky-labs.com/DB51AE99-DEDE-3B44-9EE0-F8F0A5E615CD/main.js" charset="UTF-8"></script></script>

<meta name="google-site-verification" content="Yf6alaN7IZyk5Ax9pGX8cZ7qonqyI35ehsfS6hAAND8" />

		<!--font-family-->
		<link href="https://fonts.googleapis.com/css?family=Rufina:400,700" rel="stylesheet" />

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet" />

		<!-- TITLE OF SITE -->
		<h1><title>Pawna Lake Camping in Lonavla @ starting Rs 1500 | Book now Pawna Lake Camping | Enjoy best pawna lake experience with mouthwatering BBQ, Dinner beside lake for Friends, Couples and Family.
</title></h1>

	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="Affordable pawna lake camping at lonavla near pune. you will also get cheap bunglows on rent in lonavla. Enjoy camping near pune in lonavla at thakursai pawna lake camping."/>
<meta name="keywords" content="Pawna lake camping, Pawna lake, Pavana lake, pawana lake, pavana dam Lonavala, camping near pune, pawna lake camping booking, camping in lonavala, bungalows on rent in lonavala, campgrounds near me, pawna lake resorts and camping, thakursai pawna lake camping,camping near mumbai,Places near Lonavala."/>
	<meta name="Language" content="English"/>
<meta http-equiv="Expires" content="never"/>
<meta http-equiv="CACHE-CONTROL" content="PUBLIC"/>
<meta http-equiv="PRAGMA" content=""/>
<meta name="Copyright" content="http://pawanacamps.com"/>
<meta name="Designer" content="http://pawanacamps.com"/>
<meta name="Publisher" content="http://pawanacamps.com"/>
<meta name="Revisit-After" content="perday/everyday/ allday"/>
<meta name="distribution" content="Global"/>
<meta name="Robots" content="INDEX,FOLLOW"/>
<meta name="YahooSeeker" content="INDEX, FOLLOW"/>
<meta name="msnbot" content="INDEX, FOLLOW"/>
<meta name="googlebot" content="INDEX, FOLLOW"/>
<meta name="city" content="Lonavla"/>
<meta name="country" content="India"/>	
<meta name="Geography" content="Lonavla, India"/>

<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Explore the Beauty of Pawna Lake Camping",
  "image" : "https://www.pawanacamps.com/assets/images/home/sm3.jpg",
  "priceRange" : "RS 1500 Per Person",
  "telephone" : [ "+918554078584", "+917020638029" ],
  "email" : "pavanacamps@gmail.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "Pawna Lake, Ghevande Khadak, Takursai Aajivali road",
    "addressLocality" : "Lonavla, Pune",
    "addressRegion" : "Maharashra",
    "postalCode" : "410406"
  },
  "review" : {
    "@type" : "Review",
    "reviewRating" : {
      "@type" : "Rating",
      "ratingValue" : "2544 review"
    }
  }
}
</script>


		<!-- favicon img -->
		<link rel="shortcut icon" type="image/icon" href="assets/logo/favicon.png"/>

		<!--font-awesome.min.css-->
		<link rel="stylesheet" href="assets/css/font-awesome.min.css" />

		<!--animate.css-->
		<link rel="stylesheet" href="assets/css/animate.css" />

		<!--hover.css-->
		<link rel="stylesheet" href="assets/css/hover-min.css">

		<!--datepicker.css-->
		<link rel="stylesheet"  href="assets/css/datepicker.css" >

		<!--owl.carousel.css-->
        <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
		<link rel="stylesheet" href="assets/css/owl.theme.default.min.css"/>

		<!-- range css-->
        <link rel="stylesheet" href="assets/css/jquery-ui.min.css" />

		<!--bootstrap.min.css-->
		<link rel="stylesheet" href="assets/css/bootstrap.min.css" />

		<!-- bootsnav -->
		<link rel="stylesheet" href="assets/css/bootsnav.css"/>

		<!--style.css-->
		<link rel="stylesheet" href="assets/css/style.css" />

		<!--responsive.css-->
		<link rel="stylesheet" href="assets/css/responsive.css" />

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

	</head>

	<body><div class="wrapper">
		<!--[if lte IE 9]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade
			your browser</a> to improve your experience and security.</p>
		<![endif]-->

		<!-- main-menu Start -->
		<header class="top-area">
			<div id="sticky-wrapper" class="sticky-wrapper is-sticky" style="height: 78px;"><div class="header-area" style="width: 1349px; position: fixed; top: 0px; z-index: inherit;">
				<div class="container">
					<div class="row">
						<div class="col-sm-2">
							<div class="logo">
	<img src="assets/images/home/pawanalogo.png">	
    
    <a href="index.html">Pawna<span>Camps</span></a>
							</div><!-- /.logo-->
						</div><!-- /.col-->
						
						<div class="col-sm-10">
							<div class="main-menu">
							
								<!-- Brand and toggle get grouped for better mobile display -->
								<div class="navbar-header">
									<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
										<i class="fa fa-bars"></i>
									</button><!-- / button-->
								</div><!-- /.navbar-header-->
								<div class="collapse navbar-collapse">		  
									<ul class="nav navbar-nav navbar-right">
										<li class="smooth-menu"><a href="#home">Home</a></li>
										<li class="smooth-menu active"><a href="#gallery">Destination</a></li>
										<li class="smooth-menu"><a href="#pack">Packages </a></li>
										<li class="smooth-menu"><a href="#spo">Offers</a></li>
										<li class="smooth-menu"><a href="#upcomingevents">Events</a></li>
									<!-- 	<li><a href="terms.html">Terms</a></li> -->
										<li class="smooth-menu"><a href="#subs">Contact Us</a></li>
										<li>
											


										</li><!--/.project-btn--> 
									</ul>
								</div><!-- /.navbar-collapse -->
							</div><!-- /.main-menu-->
						</div><!-- /.col-->
					</div><!-- /.row -->
					<div class="home-border"></div><!-- /.home-border-->
				</div><!-- /.container-->
			</div></div><!-- /.header-area -->

		</header><!-- /.top-area-->
		<!-- main-menu End -->

		
		<!--about-us start -->
		<section id="home" class="about-us">
			<div class="container">
				<div class="about-us-content">
					<div class="row">
						<div class="col-sm-12">
							<div class="single-about-us">
								<div class="about-us-txt">
                                                                 
									<p class="animated fadeInUp" style="opacity: 1;font-size:35px;color:white;margin-top:250px;" align="center">
										 "Pawna lake camping"<br/>
<i class="fa fa-star" style="color:#FFDF00"></i>Camp Under The Stars<i class="fa fa-star" style="color:#FFDF00"></i>

									</p>
									<div class="about-btn">
										
									</div><!--/.about-btn-->
								</div><!--/.about-us-txt-->
							</div><!--/.single-about-us-->
						</div><!--/.col-->
						<div class="col-sm-0">
							<div class="single-about-us">
								
							</div><!--/.single-about-us-->
						</div><!--/.col-->
					</div><!--/.row-->
				</div><!--/.about-us-content-->
			</div><!--/.container-->

		</section><!--/.about-us-->
		<!--about-us end -->

		

        <!--service start-->
		<section id="service" class="service">
			<div class="container">

				<div class="service-counter text-center">

					<div class="col-md-4 col-sm-4">
						<div class="single-service-box">
							<div class="service-img">
								<img src="assets/images/service/s1.png" alt="service-icon">
							</div><!--/.service-img-->
							<div class="service-content">
								<h2>
									<a href="#">
									Best and Affordable Packages
									</a>
								</h2>
								<p>Find the best pawna lake camping packages and enjoy the beauty and adventure in max Mode.</p>
							</div><!--/.service-content-->
						</div><!--/.single-service-box-->
					</div><!--/.col-->

					<div class="col-md-4 col-sm-4">
						<div class="single-service-box">
							<div class="service-img">
								<img src="assets/images/service/s2.png" alt="service-icon">
							</div><!--/.service-img-->
							<div class="service-content">
								<h2>
									<a href="#">Stay in Tents.</a>
								</h2>
								<p>Stay in 3-4 Sharing and Build your Fun in Beautiful Tents.</p>
							</div><!--/.service-content-->
						</div><!--/.single-service-box-->
					</div><!--/.col-->

					<div class="col-md-4 col-sm-4">
						<div class="single-service-box">
							<div class="statistics-img">
								<img src="assets/images/service/s3.png" alt="service-icon">
							</div><!--/.service-img-->
							<div class="service-content">

								<h2>
									<a href="#">
										Sports and Activities
									</a>
								</h2>
								<p>Cricket, Volley Ball, Chess, Climbing and Much more to enjoy at Pawna Camps.</p>
							</div><!--/.service-content-->
						</div><!--/.single-service-box-->
					</div><!--/.col-->

				</div><!--/.statistics-counter-->	
			</div><!--/.container-->

		</section><!--/.service-->
		<!--service end-->

		<!--galley start-->
		<section id="gallery" class="gallery">
			<div class="container">
				<div class="gallery-details">
					<div class="gallary-header text-center">
						<h2>  Enjoy besides Pawna lake!</h2>
	<p style="text-align:justify;">
							
Build a Camp under the stars amongst unspoilt surroundings of <b>Pawna lake. Pawna lake camping</b> offers an absolutely plain lakeside land surrounded by hills, and the most attractive pawna lake water that is beautifully and naturally decorated by forts and hills.<b> Pawanacamps locations</b> is located at <b>Pawna lake, Lonavala</b> around 55km from Pune and 110km from mumbai. Pawna lake tourism footfall is increasing day by day and pawna lake camping has reached approximately on saturation stage. We are lucky enough to explore such a new location that is perfectly fit for the <b>camping activity at pawna lake.</b> Pawana camps providing enjoyable and <b>safe camping experience</b> over 5years. Hundreds of sport events, cultural events, parties completed at pawna lake camping. Pawanacamps has all natural camping locations and some <b>locations are lake side</b> and some are on the hills. Pawna lake is surrounded by the many <b>historical forts</b> people always used to go there for <b>trekking.</b>
</p>
					</div><!--/.gallery-header-->
					<div class="gallery-box">
						<div class="gallery-content">
						  	<div class="filtr-container">
						  		<div class="row">

						  			<div class="col-md-6">
						  				<div class="filtr-item">
											<img src="assets/images/home/md1.jpg" alt="portfolio image">
											<div class="item-title">
												<a href="#">Day Adventure</a>
												<!-- <p><span>15 Tours</span><span>2 places</span></p>-->
											</div><!-- /.item-title -->
										</div><!-- /.filtr-item -->
						  			</div><!-- /.col -->

						  			<div class="col-md-6">
						  				<div class="filtr-item">
											<img src="assets/images/home/md2.jpg" alt="portfolio image">
											<div class="item-title">
												<a href="#">
													Night Life
												</a>
												
											</div> <!-- /.item-title-->
										</div><!-- /.filtr-item -->
						  			</div><!-- /.col -->

						  			<div class="col-md-4">
						  				<div class="filtr-item">
											<img src="assets/images/gallary/archery.jpg" alt="portfolio image">
											<div class="item-title">
												<a href="#">
													Sports Activity
												</a>
												
											</div><!-- /.item-title -->
										</div><!-- /.filtr-item -->
						  			</div><!-- /.col -->

						  			<div class="col-md-4">
						  				<div class="filtr-item">
											<img src="assets/images/home/md4.jpg" alt="portfolio image">
											<div class="item-title">
												<a href="#">
													Boating
												</a>
												
											</div> <!-- /.item-title-->
										</div><!-- /.filtr-item -->
						  			</div><!-- /.col -->

						  			<div class="col-md-4">
						  				<div class="filtr-item">
											<img src="assets/images/home/md5.jpg" alt="portfolio image">
											<div class="item-title">
												<a href="#">
													Darts Game
												</a>
												
											</div> <!-- /.item-title-->
										</div><!-- /.filtr-item -->
						  			</div><!-- /.col -->
						  		</div> <!-- /.row -->
		<div class="row">
						  			<div class="col-md-4">
						  				<div class="filtr-item">
						  				<img src="assets/images/home/md6.jpg" alt="portfolio image">
											<div class="item-title">
												<a href="#">
													Quality Interiors
												</a>
												
											</div> <!-- /.item-title-->
										</div><!-- /.filtr-item -->
						  			</div><!-- /.col -->

						  			<div class="col-md-4">
						  				<div class="filtr-item">
						  				<img src="assets/images/home/md7.jpg" alt="portfolio image">
											<div class="item-title">
												<a href="#">
													Barbeque Delight
												</a>
												
											</div> <!-- /.item-title-->
										</div><!-- /.filtr-item -->
						  			</div><!-- /.col -->


						<div class="col-md-4">
						  				<div class="filtr-item">
						  				
											<img src="assets/images/home/md8.jpg" alt="portfolio image">
											<div class="item-title">
												<a href="#">
													Creative Tents
												</a>
											
											</div> <!-- /.item-title-->
										</div><!-- /.filtr-item -->
						  			</div><!-- /.col -->

						  		</div><!-- /.row -->

						  	</div><!-- /.filtr-container-->
				</div>
					</div><!--/.galley-box-->
				
		</section><!--/.gallery-->
		<!--gallery end-->


		<!--discount-offer start-->
		<section class="discount-offer">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<div class="dicount-offer-content text-center">
							<h2>Discount Flat Rs.100 OFF Per person. For all locations. Valid upto 15th December 2018.</h2>
							<div class="campaign-timer">
								<div id="timer">
									<div class="time time-after" id="days">41<span class="camp">Days</span></div><!--/.time-->
									<div class="time time-after" id="hours">05<span class="camp">Hour</span></div><!--/.time-->
									<div class="time time-after" id="minutes">37<span class="camp">Minute</span></div><!--/.time-->
									<div class="time" id="seconds">16<span class="camp">Second</span></div><!--/.time-->
								</div><!--/.timer-->
							</div><!--/.campaign-timer-->
							<div class="about-btn">
								<button class="about-view discount-offer-btn">
									join now
								</button>
							</div><!--/.about-btn-->


						</div><!-- /.dicount-offer-content-->
					</div><!-- /.col-->
				</div><!-- /.row-->
			</div><!-- /.container-->

		</section><!-- /.discount-offer-->
		<!--discount-offer end-->

		<!--packages start-->
		<section id="pack" class="packages">
			<div class="container">
				<div class="gallary-header text-center">
					<h2>
						special packages
					</h2>
					<p style="text-align:justify;">Pawna lake camping regular package include unlimited food, barbecue, <b>free activities</b>, campfire and music. Pawana camps designed a affordable packages for our guest and our trained staff at campsite is equipped with necessary knowledge and skill to ensure safety of our guest. Pawna lake is national and international tourist place and because its famous for <b>camping, trekking, kayaking, sport events, cycling, adventure resorts.</b> Historical forts and <b>caves</b>, waterfalls are one the main attraction of tourists. People come for pawna lake camping for enjoy their weekends living  in tent, sit besides campfire with favourite music, to relax and forget all the worries and spent some quality time with near and dear ones. At Pawana camps locations you can bring your own camping equipment such as tent and food we can organise campsite for you. Before coming to the campsite <b>Pre-booking is necessary.</b> Checkout out simple booking procedure.</p>
					<!--<p>
						There are three different types of pawna lake camping opportunities in lonavla. Recreational Camping for people who want all the comforts of home, primitive camping for those who enjoy closer contact with nature and wilderness camping for the more adventuresome. You can find wide ranges of camping facilities all across the India in each of these categories.
Recreational camping is available at pawna lake. Most of these facilities include clean western toilets, Mineral water for Drinking, Tents including blanket, foam mat, Pillow, Bedsheet, music system(Trolley Speaker). Here you get Unlimited Vegetarian and Non-Vegetarian Home made food, Snaks etc. You can pitch your tent at such a facility and it would be great, less expensive. Pawanacamps offers many upscale recreational campgrounds near Lonavala, Pune and Mumbai. All of our facilities are usually very nice, very clean and well equipped. It cost Rs.1299 to Rs.1499  a night to stay at a well-equipped campground.
					</p>-->
				</div><!--/.gallery-header-->
				<div class="packages-content">
					<div class="row">

						<div class="col-md-4 col-sm-6">
							<div class="single-package-item">
								<img src="assets/images/pawanacampsA.jpg" alt="package-place">
								<div class="single-package-item-txt">
									<h3>CampSite A<span class="pull-right">Rs.1500/-</span></h3>
									<div class="packages-para">
										<p>
											<span>
												✔Check in : 4:30PM Check out: 11:00AM.
											</span>
											
										</p>
										
											<p>
											<span>
												✔2/3/4 Person tents. Big size tent also available
											</span>
											</p>
											<p>
											<span>
											✔Unlimited Dinner (Veg/Non-Veg).
										</span>
									</p>
									<p>
											<span>
											✔Evening Snacks (Tea+ Pakoda).
										</span>
									</p>
									<p>
											<span>
											✔Barbeque (Veg/Non-Veg 250gm/Each).
										</span>
									</p>
									<p>
											<span>
											✔Morning breakfast(Tea+Poha).
										</span>
									</p>
									<p>
											<span>
											✔Campfire(Common after dinner).
										</span>
									</p>
									<p>
											<span>
											✔Music System (9 to 12PM).
										</span>
									</p>
									<p>
											<span>
											✔Free Activities: Archery, Dart game, Carom, Volleyball, football, badminton etc.
										</span>
									</p>
									<p>
											<span>
											✔Other: Common Toilets, First aid kit.
										</span>
									</p>
										 </p>
									</div><!--/.packages-para-->
									<div class="packages-review">
										<p>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<span>124 review</span>
										</p>
									</div><!--/.packages-review-->
									<div class="about-btn">
										<button class="about-view packages-btn">
											<a href="campsite-A.html">book now</a>
										</button>
									</div><!--/.about-btn-->
								</div><!--/.single-package-item-txt-->
							</div><!--/.single-package-item-->

						</div><!--/.col-->

						<div class="col-md-4 col-sm-6">
							<div class="single-package-item">
								<img src="assets/images/pawanacampsB.jpg" alt="package-place">
								<div class="single-package-item-txt">
									<h3>CampSite B<span class="pull-right">Rs.1500/-</span></h3>
									<div class="packages-para">
										<p>
											<span>
												✔Check in : 4:30PM Check out: 11:00AM.
											</span>
											
										</p>
										
											<p>
											<span>
												✔2/3/4 Person tents. Big size tent also available
											</span>
											</p>
											<p>
											<span>
											✔Unlimited Dinner (Veg/Non-Veg).
										</span>
									</p>
									<p>
											<span>
											✔Evening Snacks (Tea+ Pakoda).
										</span>
									</p>
									<p>
											<span>
											✔Barbeque (Veg/Non-Veg 250gm/Each).
										</span>
									</p>
									<p>
											<span>
											✔Morning breakfast(Tea+Poha).
										</span>
									</p>
									<p>
											<span>
											✔Campfire(Common after dinner).
										</span>
									</p>
									<p>
											<span>
											✔Music System (9 to 12PM).
										</span>
									</p>
									<p>
											<span>
											✔Free Activities: Archery, Dart game, Carom, Volleyball, football, badminton etc.
										</span>
									</p>
									<p>
											<span>
											✔Other: Common Toilets, First aid kit.
										</span>
									</p>
										 </p>
										
									</div><!--/.packages-para-->
									<div class="packages-review">
										<p>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<span>67 review</span>
										</p>
									</div><!--/.packages-review-->
									<div class="about-btn">
										<button class="about-view packages-btn">
											<a href="campsite-B.html">book now</a>
										</button>
									</div><!--/.about-btn-->
								</div><!--/.single-package-item-txt-->
							</div><!--/.single-package-item-->

						</div><!--/.col-->
						
						<div class="col-md-4 col-sm-6">
							<div class="single-package-item">
								<img src="assets/images/pawanacampsC.jpg" alt="package-place">
								<div class="single-package-item-txt">
									<h3>CampSite C<span class="pull-right">Rs.1500/-</span></h3>
									<div class="packages-para">
										<p>
											<span>
												✔Check in : 4:30PM Check out: 11:00AM.
											</span>
											
										</p>
										
											<p>
											<span>
												✔2/3/4 Person tents. Big size tent also available
											</span>
											</p>
											<p>
											<span>
											✔Unlimited Dinner (Veg/Non-Veg).
										</span>
									</p>
									<p>
											<span>
											✔Evening Snacks (Tea+ Pakoda).
										</span>
									</p>
									<p>
											<span>
											✔Barbeque (Veg/Non-Veg 250gm/Each).
										</span>
									</p>
									<p>
											<span>
											✔Morning breakfast(Tea+Poha).
										</span>
									</p>
									<p>
											<span>
											✔Campfire(Common after dinner).
										</span>
									</p>
									<p>
											<span>
											✔Music System (9 to 12PM).
										</span>
									</p>
									<p>
											<span>
											✔Free Activities: Archery, Dart game, Carom, Volleyball, football, badminton etc.
										</span>
									</p>
									<p>
											<span>
											✔Other: Common Toilets, First aid kit.
										</span>
									</p>
										 </p>


									</div><!--/.packages-para-->
									
								
									<div class="packages-review">
										<p>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<span>232 review</span>
										</p>
									</div><!--/.packages-review-->

									
									<div class="about-btn">
										<button class="about-view packages-btn">
											<a href="campsite-C.html">book now</a>
										</button>
									</div><!--/.about-btn-->
									
								</div><!--/.single-package-item-txt-->
								
							</div><!--/.single-package-item-->
				
						</div><!--/.col-->
						<!-- Extra 
						<div class="col-md-4 col-sm-6">
							<div class="single-package-item">
								<img src="assets/images/packages/p4.jpg" alt="package-place">
								<div class="single-package-item-txt">
									<h3>india <span class="pull-right">$799</span></h3>
									<div class="packages-para">
										<p>
											<span>
												<i class="fa fa-angle-right"></i> 5 daays 6 nights
											</span>
											<i class="fa fa-angle-right"></i>  5 star accomodation
										</p>
										<p>
											<span>
												<i class="fa fa-angle-right"></i>  transportation
											</span>
											<i class="fa fa-angle-right"></i>  food facilities
										 </p>
									</div><!--/.packages-para-->
									<!-- Extra 
									<div class="packages-review">
										<p>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<span>2544 review</span>
										</p>
									</div><!--/.packages-review-->
									<!-- Extra 
									<div class="about-btn">
										<button class="about-view packages-btn">
											book now
										</button>
									</div><!--/.about-btn-->
									<!-- Extra 
								</div><!--/.single-package-item-txt-->
								<!-- Extra 
							</div><!--/.single-package-item-->
<!-- Extra 
						</div><!--/.col-->
						<!-- Extra 
						<div class="col-md-4 col-sm-6">
							<div class="single-package-item">
								<img src="assets/images/packages/p5.jpg" alt="package-place">
								<div class="single-package-item-txt">
									<h3>spain <span class="pull-right">$999</span></h3>
									<div class="packages-para">
										<p>
											<span>
												<i class="fa fa-angle-right"></i> 5 daays 6 nights
											</span>
											<i class="fa fa-angle-right"></i>  5 star accomodation
										</p>
										<p>
											<span>
												<i class="fa fa-angle-right"></i>  transportation
											</span>
											<i class="fa fa-angle-right"></i>  food facilities
										 </p>
									</div><!--/.packages-para-->
									<!-- Extra 
									<div class="packages-review">
										<p>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<span>2544 review</span>
										</p>
									</div><!--/.packages-review-->
									<!-- Extra 
									<div class="about-btn">
										<button class="about-view packages-btn">
											book now
										</button>
									</div><!--/.about-btn-->
									<!-- Extra 
								</div><!--/.single-package-item-txt-->
								<!-- Extra 
							</div><!--/.single-package-item-->
<!-- Extra 
						</div><!--/.col-->
						<!-- Extra 
						<div class="col-md-4 col-sm-6">
							<div class="single-package-item">
								<img src="assets/images/packages/p6.jpg" alt="package-place">
								<div class="single-package-item-txt">
									<h3>thailand <span class="pull-right">$799</span></h3>
									<div class="packages-para">
										<p>
											<span>
												<i class="fa fa-angle-right"></i> 5 daays 6 nights
											</span>
											<i class="fa fa-angle-right"></i>  5 star accomodation
										</p>
										<p>
											<span>
												<i class="fa fa-angle-right"></i>  transportation
											</span>
											<i class="fa fa-angle-right"></i>  food facilities
										 </p>
									</div><!--/.packages-para-->
									<!-- Extra 
									<div class="packages-review">
										<p>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<span>2544 review</span>
										</p>
									</div><!--/.packages-review-->
									<!-- Extra 
									<div class="about-btn">
										<button class="about-view packages-btn">
											book now
										</button>
									</div><!--/.about-btn-->
									<!-- Extra 
								</div><!--/.single-package-item-txt-->
								<!-- Extra 
							</div><!--/.single-package-item-->

						</div><!--/.col-->

					</div><!--/.row-->
				</div><!--/.packages-content-->
			</div><!--/.container-->

		</section><!--/.packages-->
		<!--packages end-->

		<!-- testemonial Start -->
		
		<section class="testemonial">
			<div class="container">

				<div class="gallary-header text-center">
					<h2>
						Checkout our Special Offers Daily!
					</h2>
					<p>
						We Offer Best Deals to our customers for pawna camping. 
					</p>

				</div><!--/.gallery-header-->
<!--
				<div class="owl-carousel owl-theme owl-loaded owl-drag" id="testemonial-carousel">

					<!--/.item-->

					<!--/.item-->

					<!--/.item-->

					<!--/.item-->

					<!--/.item-->

					<!--/.item-->

					<!--/.item-->

					<!--/.item-->

					<!--/.item-->
<!--
				<div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-2280px, 0px, 0px); transition: all 0s ease 0s; width: 7220px;"><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial2.jpg" alt="img">
							</div><!--/.home1-testm-img-->
							<!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
							<!--
						</div><!--/.home1-testm-single-->
<!--
					</div></div><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img-->

							<!--

							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	

							<!--

						</div><!--/.home1-testm-single-->
<!--
					</div></div><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img-->
							
							<!--

							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial2.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single-->
<!--
					</div></div><div class="owl-item" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4><!--
							</div><!--/.home1-testm-txt-->	<!--
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item active" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial2.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	<!--
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item active" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item active" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial2.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	<!--
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial2.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	<!--
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial2.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	
						</div><!--/.home1-testm-single--><!--

					</div></div><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
							</div><!--/.home1-testm-txt-->	<!--
						</div><!--/.home1-testm-single-->
<!--
					</div></div><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial1.jpg" alt="img">
							<!--</div><!--/.home1-testm-img--><!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<!--<h4>london, england</h4>
						<!--	</div><!--/.home1-testm-txt-->	
						<!--</div><!--/.home1-testm-single-->
<!--
					</div></div><div class="owl-item cloned" style="width: 380px;"><div class="home1-testm item">
						<div class="home1-testm-single text-center">
							<div class="home1-testm-img">
								<img src="assets/images/client/testimonial2.jpg" alt="img">
							</div><!--/.home1-testm-img-->
							<!--
							<div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
								<p>
									Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
								</p>
								<h3>
									<a href="#">
										kevin watson
									</a>
								</h3>
								<h4>london, england</h4>
								<!--
							</div><!--/.home1-testm-txt-->	
							<!--
						</div><!--/.home1-testm-single-->
<!--
					</div></div></div></div><div class="owl-nav disabled"><div class="owl-prev">prev</div><div class="owl-next">next</div></div><div class="owl-dots"><div class="owl-dot active"><span></span></div><div class="owl-dot"><span></span></div><div class="owl-dot"><span></span></div></div></div><!--/.testemonial-carousel-->
			
			</div><!--/.container-->
	</section><!--/.testimonial-->	
		<!-- testemonial End -->


		<!--special-offer start-->
		<section id="spo" class="special-offer">
			<div class="container">
				<div class="special-offer-content">
					<div class="row">
						<div class="col-sm-8">
							<div class="single-special-offer">
								<div class="single-special-offer-txt">
									<h2>Pawna Lake Side Camping</h2>
									<div class="packages-review special-offer-review">
										<p>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<span>65 People showed Interest</span>
										</p>
									</div><!--/.packages-review-->
									<div class="packages-para special-offer-para">
										<p>
											<span>
												<i class="fa fa-angle-right"></i> 1 Night
											</span>
											<span>
												<i class="fa fa-angle-right"></i> 1 person
											</span>
											<span>
												<i class="fa fa-angle-right"></i>  3 person accomodation
											</span>
										</p>
										<p>
											<span>
												<i class="fa fa-angle-right"></i>  Games Facilities
											</span>
											<span>
												<i class="fa fa-angle-right"></i>  Food facilities
											</span>  
										</p>
										<p class="offer-para">
											<b>Pawnacamps strongly recommend you to find us as one of the best service providers for camping in Lonavala, near Pune and forget all your worries in a spectacular holiday spot.</b>

										</p>
									</div><!--/.packages-para-->
									<div class="offer-btn-group">
										
										<a href="#subs"><div class="about-btn">
											<button class="about-view packages-btn">
												Call now
											</button>
										</div></a><!--/.about-btn-->
									</div><!--/.offer-btn-group-->
								</div><!--/.single-special-offer-txt-->
							</div><!--/.single-special-offer-->
						</div><!--/.col-->
						<div class="col-sm-4">
							<div class="single-special-offer">
								<div class="single-special-offer-bg">
									<img src="assets/images/offer/pawna-verticle.jpg" alt="offer-shape">
								</div><!--/.single-special-offer-bg-->
								<div class="single-special-shape-txt">
									<h3>special offer</h3>
									<!--<h4><span>40%</span><br>off</h4>-->
									<p><span>FLAT RS 100 off</span><br>regular RS 1500 <br>now RS 1400</p>
								</div><!--/.single-special-shape-txt-->
							</div><!--/.single-special-offer-->
						</div><!--/.col-->
					</div><!--/.row-->
				</div><!--/.special-offer-content-->
			</div><!--/.container-->

		</section><!--/.special-offer end-->
		<!--special-offer end-->









<!--Upcoming start-->
		<section id="upcomingevents" class="upcoming">
			<div class="container">
				<div class="gallary-header text-center ind">
					<h2 class="ind">
						Upcoming Events
					</h2>
					<p class="ind" style="text-align:justify;">
						Trekking in Pawna is one of the best things to do over a weekend. The area is surrounded by stunning mountain ranges and greenery. Boating, Night Out, Camping, Sports are some of the best things to do. If you are an adventure junkie, the best is to trek up the forts, do some camping at the best trekking places in Pawna.
					</p>
				</div><!--/.gallery-header-->
				<div class="upcoming-content ind">
					

						
						
				</div><!--/.upcoming-content-->
			</div><!--/.container-->

		</section><!--/.upcoming-->
		<!--upcoming end-->



















		<!--blog start-->
		<!--
		<section id="blog" class="blog">
			<div class="container">
				<div class="blog-details">
						<div class="gallary-header text-center">
							<h2>
								latest news
							</h2>
							<p>
								Travel News from all over the world 
							</p>
						</div><!--/.gallery-header--><!--
						<div class="blog-content">
							<div class="row">

								<div class="col-sm-4 col-md-4">
									<div class="thumbnail">
										<h2>trending news <span>15 november 2017</span></h2>
										<div class="thumbnail-img">
											<img src="assets/images/blog/b1.jpg" alt="blog-img">
											<div class="thumbnail-img-overlay"></div><!--/.thumbnail-img-overlay--><!--
										
										</div><!--/.thumbnail-img-->
									  <!--
										<div class="caption">
											<div class="blog-txt">
												<h3>
													<a href="#">
														Discover on beautiful weather, Fantastic foods and historical place in Prag
													</a>
												</h3>
												<p>
													Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam 
												</p>
												<a href="#">Read More</a>
											</div><!--/.blog-txt--><!--
										</div><!--/.caption--><!--
									</div><!--/.thumbnail--><!--

								</div><!--/.col-->
<!--
								<div class="col-sm-4 col-md-4">
									<div class="thumbnail">
										<h2>trending news <span>15 november 2017</span></h2>
										<div class="thumbnail-img">
											<img src="assets/images/blog/b2.jpg" alt="blog-img">
											<div class="thumbnail-img-overlay"></div><!--/.thumbnail-img-overlay--><!--
										
										</div><!--/.thumbnail-img--><!--
										<div class="caption">
											<div class="blog-txt">
												<h3>
													<a href="#">
														Discover on beautiful weather, Fantastic foods and historical place in india
													</a>
												</h3>
												<p>
													Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam 
												</p>
												<a href="#">Read More</a>
											</div><!--/.blog-txt--><!--
										</div><!--/.caption--><!--
									</div><!--/.thumbnail--><!--

								</div><!--/.col--><!--

								<div class="col-sm-4 col-md-4">
									<div class="thumbnail">
										<h2>trending news <span>15 november 2017</span></h2>
										<div class="thumbnail-img">
											<img src="assets/images/blog/b3.jpg" alt="blog-img">
											<div class="thumbnail-img-overlay"></div><!--/.thumbnail-img-overlay--><!--
										
										</div><!--/.thumbnail-img--><!--
										<div class="caption">
											<div class="blog-txt">
												<h3><a href="#">10 Most Natural place to Discover</a></h3>
												<p>
													Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam 
												</p>
												<a href="#">Read More</a>
											</div><!--/.blog-txt--><!--
										</div><!--/.caption--><!--
									</div><!--/.thumbnail--><!--

								</div><!--/.col--><!--

							</div><!--/.row--><!--
						</div><!--/.blog-content--><!--
					</div><!--/.blog-details--><!--
				</div><!--/.container--><!--

		</section><!--/.blog-->
		<!--blog end-->

		
		
		
		
		
		
		
		<!--subscribe start-->
		<section id="subs" class="subscribe">
			<div class="container">
				<div class="subscribe-title text-center">
					<h2>
						Join our Subscribers List to Get Regular Update
					</h2>
					<p>
						Subscribe Now. We will send you Best offer for your Trip 
					</p>
				</div>
				<form>
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
							<div class="custom-input-group">
								<input type="email" class="form-control" placeholder="Enter your Email Here">
								<button class="appsLand-btn subscribe-btn">Subscribe</button>
								<div class="clearfix"></div>
								<i class="fa fa-envelope"></i>
							</div>

						</div>
					</div>
				</form>
			</div>

		</section>
		<!--subscribe end-->
		

		<!-- footer-copyright start -->
		<footer class="footer-copyright">
			<div>
				<a href="https://wa.me/send?phone=917020638029&amp;text= I'm contacting you by clicking on the WhatsApp button of your website: http://www.pawanacamps.com. My name is"><img class="whatsapp" src="assets/images/home/whatsapp.png" alt="Whatsapp Chat"></img></a>
			</div>
			<div class="container">
				<div class="footer-content">
					<div class="row">

						<div class="col-sm-3">
							<div class="single-footer-item">
								<div class="footer-logo">
									<a href="index.html">
										Pawna<span>Camps</span>
									</a>
									<p>
										best camping spot
									</p>
								</div>
							</div><!--/.single-footer-item-->
						</div><!--/.col-->

						<div class="col-sm-3">
							<div class="single-footer-item">
								<h2>link</h2>
								<div class="single-footer-txt">
									<p class="scroll-1"><a href="#home">Home</a></p>
									<p class="scroll-2"><a href="#gallery">Destination</a></p>
									<p class="scroll-3"><a href="#pack">Special Packages</a></p>
									<p class="scroll-4"><a href="#spo">Special Offers</a></p>
									<p class="scroll-5"><a href="#upcomingevents">Upcoming Events</a></p>
									<!-- <p class="scroll-6"><a href="terms.html">Terms & Policy</a></p> -->
									<p class="scroll-7"><a href="#subs">Contacts</a></p>
								</div><!--/.single-footer-txt-->
							</div><!--/.single-footer-item-->

						</div><!--/.col-->

						<div class="col-sm-3">
							<div class="single-footer-item">
								<h2>popular destination</h2>
								<div class="single-footer-txt">
									<p><a href="#">Mumbai</a></p>
									<p><a href="#">Pune</a></p>
									<p><a href="#">Goa</a></p>
									<p><a href="#">Lonavla</a></p>
									<p><a href="#">Pawna</a></p>
								</div><!--/.single-footer-txt-->
							</div><!--/.single-footer-item-->
						</div><!--/.col-->

						<div class="col-sm-3">
							<div class="single-footer-item text-center">
								<h2 class="text-left">contacts</h2>
								<div class="single-footer-txt text-left">
									<p><span style="background-color: #FFFF00;font-size:22px;">+91-8554078584 <br> +91-8605308092</span></p>
									<p class="foot-email"><a href="#">pavanacamps@gmail.com</a></p>
									<p>Pawna Lake, Ghevande Khadak, Takursai Aajivali road</p>
									<p>Lonavla, Pune, Maharashra - 410406</p>
								</div><!--/.single-footer-txt-->
							</div><!--/.single-footer-item-->
						</div><!--/.col-->

					</div><!--/.row-->

				</div><!--/.footer-content-->
				<hr>
				<div class="foot-icons ">
					<ul class="footer-social-links list-inline list-unstyled">
		                <li><a href=" https://m.facebook.com/pawana.camps" target="_blank" class="foot-icon-bg-1"><i class="fa fa-facebook"></i></a></li>
		                <li><a href="https://mobile.twitter.com/CampsPawana" target="_blank" class="foot-icon-bg-2"><i class="fa fa-twitter"></i></a></li>
		                <li><a href="https://www.instagram.com/pawnacamps/" target="_blank" class="foot-icon-bg-3"><i class="fa fa-instagram"></i></a></li>
		                <li><a href="https://www.tumblr.com/blog/pawnacamps" target="_blank" class="foot-icon-bg-2"><i class="fa fa-tumblr"></i></a></li>
		                <li><a href="https://www.pinterest.com/pavanacamps/" target="_blank" class="foot-icon-bg-3"><i class="fa fa-pinterest"></i></a></li>
		        	</ul>
		        <!-- 	<p>© 2018 <a href="https://www.7patterns.in">BrandMarkTechnology</a>. All Right Reserved</p> -->

		        </div><!--/.foot-icons-->
				<div id="scroll-Top">
					<i class="fa fa-angle-double-up return-to-top" id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true" style="display: inline;"></i>
				</div><!--/.scroll-Top-->
			</div><!-- /.container-->

		</footer><!-- /.footer-copyright-->
		<!-- footer-copyright end -->




		<script src="assets/js/jquery.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->

		<!--modernizr.min.js-->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>


		<!--bootstrap.min.js-->
		<script src="assets/js/bootstrap.min.js"></script>

		<!-- bootsnav js -->
		<script src="assets/js/bootsnav.js"></script>

		<!-- jquery.filterizr.min.js -->
		<script src="assets/js/jquery.filterizr.min.js"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

		<!--jquery-ui.min.js-->
        <script src="assets/js/jquery-ui.min.js"></script>

        <!-- counter js -->
		<script src="assets/js/jquery.counterup.min.js"></script>
		<script src="assets/js/waypoints.min.js"></script>

		<!--owl.carousel.js-->
        <script src="assets/js/owl.carousel.min.js"></script>

        <!-- jquery.sticky.js -->
		<script src="assets/js/jquery.sticky.js"></script>

        <!--datepicker.js-->
        <script src="assets/js/datepicker.js"></script>

		<!--Custom JS-->
		<script src="assets/js/custom.js"></script>


	

</div></body>

</html>