<!doctype html>
<html class="no-js"  lang="en">
	<head>
		<!-- META DATA -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</script>
<meta name="google-site-verification" content="Yf6alaN7IZyk5Ax9pGX8cZ7qonqyI35ehsfS6hAAND8" />
		<!--font-family-->
		<link href="https://fonts.googleapis.com/css?family=Rufina:400,700" rel="stylesheet" />
		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
		<!-- TITLE OF SITE -->
		<h1><title>Pawna Lake Camping in Lonavla @ starting Rs 1500 | Book now Pawna Lake Camping | Enjoy best pawna lake experience with mouthwatering BBQ, Dinner beside lake for Friends, Couples and Family.
</title></h1>
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="Affordable pawna lake camping at lonavla near pune. you will also get cheap bunglows on rent in lonavla. Enjoy camping near pune in lonavla at thakursai pawna lake camping."/>
<meta name="keywords" content="Pawna lake camping, Pawna lake, Pavana lake, pawana lake, pavana dam Lonavala, camping near pune, pawna lake camping booking, camping in lonavala, bungalows on rent in lonavala, campgrounds near me, pawna lake resorts and camping, thakursai pawna lake camping,camping near mumbai,Places near Lonavala."/>
	<meta name="Language" content="English"/>
<meta http-equiv="Expires" content="never"/>
<meta http-equiv="CACHE-CONTROL" content="PUBLIC"/>
<meta http-equiv="PRAGMA" content=""/>
<meta name="Copyright" content="http://pawanacamps.com"/>
<meta name="Designer" content="http://pawanacamps.com"/>
<meta name="Publisher" content="http://pawanacamps.com"/>
<meta name="Revisit-After" content="perday/everyday/ allday"/>
<meta name="distribution" content="Global"/>
<meta name="Robots" content="INDEX,FOLLOW"/>
<meta name="YahooSeeker" content="INDEX, FOLLOW"/>
<meta name="msnbot" content="INDEX, FOLLOW"/>
<meta name="googlebot" content="INDEX, FOLLOW"/>
<meta name="city" content="Lonavla"/>
<meta name="country" content="India"/>	
<meta name="Geography" content="Lonavla, India"/>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Explore the Beauty of Pawna Lake Camping",
  "image" : "https://www.pawanacamps.com/assets/images/home/sm3.jpg",
  "priceRange" : "RS 1500 Per Person",
  "telephone" : [ "+918554078584", "+917020638029" ],
  "email" : "pavanacamps@gmail.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "Pawna Lake, Ghevande Khadak, Takursai Aajivali road",
    "addressLocality" : "Lonavla, Pune",
    "addressRegion" : "Maharashra",
    "postalCode" : "410406"
  },
  "review" : {
    "@type" : "Review",
    "reviewRating" : {
      "@type" : "Rating",
      "ratingValue" : "2544 review"
    }
  }
}
</script>
		<!-- favicon img -->
		<link rel="shortcut icon" type="image/icon" href="assets/logo/favicon.png"/>
		<!--font-awesome.min.css-->
		<link rel="stylesheet" href="assets/css/font-awesome.min.css" />
		<!--animate.css-->
		<link rel="stylesheet" href="assets/css/animate.css" />
		<!--hover.css-->
		<link rel="stylesheet" href="assets/css/hover-min.css">
		<!--datepicker.css-->
		<link rel="stylesheet"  href="assets/css/datepicker.css" >
		<!--owl.carousel.css-->
        <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
		<link rel="stylesheet" href="assets/css/owl.theme.default.min.css"/>
		<!-- range css-->
        <link rel="stylesheet" href="assets/css/jquery-ui.min.css" />
		<!--bootstrap.min.css-->
		<link rel="stylesheet" href="assets/css/bootstrap.min.css" />
		<!-- bootsnav -->
		<link rel="stylesheet" href="assets/css/bootsnav.css"/>
		<!--style.css-->
		<link rel="stylesheet" href="assets/css/style.css" />
		<!--responsive.css-->
		<link rel="stylesheet" href="assets/css/responsive.css" />
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>